# Generated by Django 2.2.12 on 2020-05-16 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('by_name', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='names',
        ),
    ]
