# Generated by Django 2.2.12 on 2020-05-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombres', models.TextField(max_length=100, unique=True)),
                ('Nombres2', models.TextField(max_length=100)),
                ('Genero', models.TextField(max_length=6)),
                ('Probabilidad', models.IntegerField()),
                ('Frecuencia', models.IntegerField()),
                ('Pais', models.TextField(max_length=100)),
                ('EdadMedia', models.IntegerField()),
            ],
        ),
    ]
