# Generated by Django 2.2.12 on 2020-05-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('by_name', '0002_auto_20200529_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='EdadMedia',
            field=models.FloatField(),
        ),
    ]
